import request from 'supertest';
import app from '../../src/app';

const E2E = process.env.DB_E2E === 'true';
const maybe = E2E ? describe : describe.skip;

type LoginResult = { accessToken: string };

type Business = { id: string; businessType: 'RETAIL' | 'RESTAURANT'; name: string };

type Product = { id: string; name: string; basePrice: number; effectivePrice: number; promoDiscountAmount: number; appliedPromo: { id: string } | null };

type OutletsList = {
  data: {
    items: Array<{ id: string }>;
  };
};

type CreatePromoResp = { data: { id: string } };

maybe('Promos E2E (DB-backed)', () => {
  let token = '';
  let businessId = '';
  let outletA = '';
  let outletB = '';
  let productId = '';

  it('login as superadmin retail', async () => {
    const res = await request(app)
      .post('/api/auth/login')
      .send({ email: 'superadmin-retail@pos.local', password: 'password123' });
    expect(res.status).toBe(200);
    const data = res.body?.data as LoginResult;
    token = data.accessToken;
    expect(typeof token).toBe('string');
  });

  it('pick RETAIL business and two outlets', async () => {
    const bizRes = await request(app)
      .get('/api/platform/businesses')
      .set('Authorization', `Bearer ${token}`);
    expect(bizRes.status).toBe(200);
    const businesses = bizRes.body?.data as Business[];
    const retail = businesses.find(b => b.businessType === 'RETAIL');
    expect(retail).toBeTruthy();
    businessId = retail!.id;

    const outletsRes = await request(app)
      .get('/api/business/outlets')
      .set('Authorization', `Bearer ${token}`)
      .set('x-business-id', businessId);
    expect(outletsRes.status).toBe(200);
    const outlets = (outletsRes.body as OutletsList).data.items;
    expect(outlets.length).toBeGreaterThan(0);
    outletA = outlets[0].id;
    outletB = outlets[1]?.id || outlets[0].id; // fallback jika hanya 1 outlet
  });

  it('pick a product', async () => {
    const res = await request(app)
      .get('/api/products')
      .query({ outletId: outletA, page: 1, perPage: 5 })
      .set('Authorization', `Bearer ${token}`)
      .set('x-business-id', businessId);

    expect(res.status).toBe(200);
    const items = res.body?.data as Product[];
    expect(items.length).toBeGreaterThan(0);
    const p = items.find(x => x.basePrice > 0) || items[0];
    productId = p.id;
  });

  let promoId = '';

  it('create a product promo (selected outlet only)', async () => {
    const body = {
      name: 'E2E Product Promo',
      description: 'Auto-generated by e2e',
      targetType: 'PRODUCT',
      productId,
      discountType: 'FIXED_AMOUNT',
      discountValue: 1000,
      startDate: '2000-01-01',
      endDate: '2099-12-31',
      startTime: '00:00',
      endTime: '23:59',
      status: 'ACTIVE',
      outletScope: 'SELECTED_OUTLETS',
      selectedOutletIds: [outletA],
    } as const;

    const res = await request(app)
      .post('/api/promos')
      .set('Authorization', `Bearer ${token}`)
      .set('x-business-id', businessId)
      .send(body);

    expect(res.status).toBe(201);
    promoId = (res.body as CreatePromoResp).data.id;
    expect(typeof promoId).toBe('string');
  });

  it('product shows discount on selected outlet, not on other outlet', async () => {
    const resA = await request(app)
      .get('/api/products')
      .query({ outletId: outletA, page: 1, perPage: 20 })
      .set('Authorization', `Bearer ${token}`)
      .set('x-business-id', businessId);
    expect(resA.status).toBe(200);
    const listA = resA.body?.data as Product[];
    const prodA = listA.find(p => p.id === productId)!;
    expect(prodA).toBeTruthy();
    expect(prodA.appliedPromo?.id).toBe(promoId);
    expect(prodA.promoDiscountAmount).toBeGreaterThanOrEqual(1000);
    expect(Math.round(prodA.effectivePrice + prodA.promoDiscountAmount)).toBe(Math.round(prodA.basePrice));

    const resB = await request(app)
      .get('/api/products')
      .query({ outletId: outletB, page: 1, perPage: 20 })
      .set('Authorization', `Bearer ${token}`)
      .set('x-business-id', businessId);
    expect(resB.status).toBe(200);
    const listB = resB.body?.data as Product[];
    const prodB = listB.find(p => p.id === productId)!;
    expect(prodB).toBeTruthy();
    if (outletB !== outletA) {
      expect(prodB.appliedPromo?.id).not.toBe(promoId);
    }
  });
});
